require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/mysteries", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Mystery. As you add validations to Mystery, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Mystery.create! valid_attributes
      get mysteries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      mystery = Mystery.create! valid_attributes
      get mystery_url(mystery)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_mystery_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      mystery = Mystery.create! valid_attributes
      get edit_mystery_url(mystery)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Mystery" do
        expect {
          post mysteries_url, params: { mystery: valid_attributes }
        }.to change(Mystery, :count).by(1)
      end

      it "redirects to the created mystery" do
        post mysteries_url, params: { mystery: valid_attributes }
        expect(response).to redirect_to(mystery_url(Mystery.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Mystery" do
        expect {
          post mysteries_url, params: { mystery: invalid_attributes }
        }.to change(Mystery, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post mysteries_url, params: { mystery: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mystery" do
        mystery = Mystery.create! valid_attributes
        patch mystery_url(mystery), params: { mystery: new_attributes }
        mystery.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the mystery" do
        mystery = Mystery.create! valid_attributes
        patch mystery_url(mystery), params: { mystery: new_attributes }
        mystery.reload
        expect(response).to redirect_to(mystery_url(mystery))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        mystery = Mystery.create! valid_attributes
        patch mystery_url(mystery), params: { mystery: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested mystery" do
      mystery = Mystery.create! valid_attributes
      expect {
        delete mystery_url(mystery)
      }.to change(Mystery, :count).by(-1)
    end

    it "redirects to the mysteries list" do
      mystery = Mystery.create! valid_attributes
      delete mystery_url(mystery)
      expect(response).to redirect_to(mysteries_url)
    end
  end
end
